# Generated by Django 2.1.4 on 2018-12-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastSearchPeptide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peptide', models.CharField(max_length=50, verbose_name='Peptit')),
                ('label', models.BooleanField(verbose_name='Etiket')),
                ('length', models.IntegerField(verbose_name='Uzunluk')),
            ],
        ),
        migrations.CreateModel(
            name='Peptides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peptide', models.CharField(max_length=50, verbose_name='Peptit')),
                ('label', models.BooleanField(verbose_name='Etiket')),
                ('length', models.IntegerField(verbose_name='Uzunluk')),
                ('time', models.DateTimeField(verbose_name='Tarih')),
            ],
        ),
    ]
